[build]
builder = "NIXPACKS"
# buildEnvironment = "V2"
nixpacksConfigPath = "buildFiles/nixpacks.build.pnpm.toml"

[deploy]
# region = "europe-west4"
runtime = "V2"
numReplicas = 1
healthcheckPath = "/health"
healthcheckTimeout = 120
# sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
