# providers = []
# buildImage = 'ghcr.io/railwayapp/nixpacks:ubuntu-1722902622'

# [variables]
# CI = 'true'
# NIXPACKS_METADATA = 'node'
# NODE_ENV = 'production'
# NPM_CONFIG_PRODUCTION = 'false'

# [phases.setup]
# nixPkgs = [
#     'nodejs_18',
#     'pnpm-8_x',
# ]
# nixLibs = [
#     'libuuid',
#     'libGL',
# ]
# nixOverlays = ['https://github.com/railwayapp/nix-npm-overlay/archive/main.tar.gz']
# nixpkgsArchive = 'e05605ec414618eab4a7a6aea8b38f6fbbcc8f08'

# [phases.install]
# dependsOn = ['setup']
# cmds = ['pnpm install --prod']
# cacheDirectories = ['/root/.local/share/pnpm/store/v3']
# paths = ['/app/node_modules/.bin']

# [phases.build]
# dependsOn = ['install']
# cmds = ['pnpm run build']
# cacheDirectories = [
#     '.next/cache',
#     'node_modules/.cache',
# ]

# [start]
# cmd = 'pnpm run payload migrate & pnpm run start'





# providers = []
# buildImage = 'ghcr.io/railwayapp/nixpacks:ubuntu-1722902622'

# [variables]
# CI = 'true'
# NIXPACKS_METADATA = 'node'
# NODE_ENV = 'production'
# NPM_CONFIG_PRODUCTION = 'false'
# PORT = '3000'

# [phases.setup]
# nixPkgs = [
#     'nodejs_22',
#     'pnpm-8_x',
#     'openssl',
# ]
# nixLibs = ['gcc-unwrapped']
# nixOverlays = ['https://github.com/railwayapp/nix-npm-overlay/archive/main.tar.gz']
# nixpkgsArchive = 'e05605ec414618eab4a7a6aea8b38f6fbbcc8f08'

# [phases.install]
# dependsOn = ['setup']
# cmds = ['pnpm install --prod']
# cacheDirectories = ['/root/.local/share/pnpm/store/v3']
# paths = ['/app/node_modules/.bin']

# [phases.build]
# dependsOn = ['install']
# cmds = ['pnpm run cross-env NODE_OPTIONS=--no-deprecation next build']
# cacheDirectories = [
#     '.next/cache',
#     'node_modules/.cache',
# ]

# [start]
# cmd = 'pnpm run cross-env NODE_OPTIONS=--no-deprecation next start -p 3000'





providers = []
buildImage = 'ghcr.io/railwayapp/nixpacks:ubuntu-1722902622'

[variables]
CI = 'true'
NIXPACKS_METADATA = 'node'
NODE_ENV = 'production'
NPM_CONFIG_PRODUCTION = 'false'
[phases.build]
dependsOn = ['install']
cmds = ['pnpm run build']
cacheDirectories = [
    '.next/cache',
    'node_modules/.cache',
]

[phases.install]
dependsOn = ['setup']
cmds = ['pnpm i --frozen-lockfile']
cacheDirectories = ['/root/.local/share/pnpm/store/v3']
paths = ['/app/node_modules/.bin']

[phases.setup]
nixPkgs = [
    'nodejs_22',
    'pnpm-8_x',
    'openssl',
]
nixLibs = ['gcc-unwrapped']
nixOverlays = ['https://github.com/railwayapp/nix-npm-overlay/archive/main.tar.gz']
nixpkgsArchive = 'e05605ec414618eab4a7a6aea8b38f6fbbcc8f08'

[start]
cmd = 'pnpm run payload migrate && pnpm run start'